name = "uk-ecommerce-shopify"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages configuration
pages_build_output_dir = "dist"

[env.production]
name = "uk-ecommerce-shopify"

[env.development]
name = "uk-ecommerce-shopify-dev"

# Environment variables (these will be set in the Cloudflare dashboard)
# Do not put sensitive values here - use the Cloudflare dashboard instead
[vars]
NODE_ENV = "production"
