name = "uk-ecommerce-shopify"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages configuration
pages_build_output_dir = "dist"

[env.production]
name = "uk-ecommerce-shopify"

[env.production.vars]
NODE_ENV = "production"

[env.preview]
name = "uk-ecommerce-shopify-preview"

[env.preview.vars]
NODE_ENV = "development"
